from enum import Enum


class IssueStatusEnum(str, Enum):
    """이슈 처리 상태 Enum"""
    PENDING_INFO_GENERATION = "PENDING_INFO_GENERATION"
    INFO_GENERATION_TRIGGERED = "INFO_GENERATION_TRIGGERED"
    INFO_GENERATION_1_COMPLETED = "INFO_GENERATION_1_COMPLETED"
    INFO_GENERATION_2_COMPLETED = "INFO_GENERATION_2_COMPLETED"
    INFO_GENERATION_3_COMPLETED = "INFO_GENERATION_3_COMPLETED"
    INFO_GENERATION_FAILED = "INFO_GENERATION_FAILED"
    IMAGE_GENERATION_TRIGGERED = "IMAGE_GENERATION_TRIGGERED"
    IMAGE_GENERATION_COMPLETED = "IMAGE_GENERATION_COMPLETED"
    IMAGE_GENERATION_FAILED = "IMAGE_GENERATION_FAILED"
